# Generated by Django 4.1.4 on 2022-12-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.IntegerField()),
                ('product_query_name', models.CharField(max_length=200)),
                ('product_scrap_name', models.CharField(max_length=200)),
                ('product_link', models.CharField(max_length=200)),
                ('product_link_img', models.CharField(max_length=200)),
                ('product_price', models.CharField(max_length=200)),
                ('product_country', models.CharField(max_length=200)),
                ('product_quality', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=70)),
                ('product_platform', models.CharField(max_length=70)),
            ],
        ),
    ]
