# Generated by Django 4.1.4 on 2022-12-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_scrapproduct_query_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapproduct',
            name='query_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
