# Generated by Django 4.1.4 on 2023-01-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_alter_scrapproduct_query_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('delivery_time_days', models.IntegerField()),
                ('delivery_time_text', models.CharField(max_length=255)),
            ],
        ),
    ]
